language: java
sudo: false
install: true

addons:
  sonarqube:
    token:
      secure: "LVPaimLD8xhRc/Gfd4E3MPqwhzricCQQpE3DnP0CpG++mNErpFWzQKWDgzjH+zVm8XizLKlWJBuFMXr4vw5b5YLt94FePiG5oLGsyJNIQddp7rrN5TeU7MPYqil78B7X7XGQ2aMBemWFVD5Pej7C+iFMSWmKiTu8Tw3NKTFC7LNbqs/GVVxZHOi10JXIm82K7K7tWP0r7/EhH2jac8ius3o2juBFUwvCAatSRoAdK4vgORa2fJYMAxZmnEln5MjuD2h21wUSNeCCuvNsc7D+bHPkEyO582J4Ub460SzKIciF9r2Bj/t2cDWCaWwfiLltuSqKAuKfqkE0kXE00hisqy/uS7nKQxzSO7wPuuxi/OGtL/YFPM0H/752ffgXdH8f/w+2D06vtMCcA61oGT74a2TfE8rHiPJ2d5QRsaumIwpP6uoTvDXvKQNk1uEtzWrcwCDASm9AO4O4QoU54TvF0LRMsT5LQ9fVyo+sGO5WnEpiPZ6ipAP4Zeulyq52UDITTb9sC/QsFu7BRClzIf1OuiXTC1mp0Aw4mfnIbjnoBcNvshJXN6+sG/Y0fOpIZz46qnvKd54ZI/ay/s24H8CnHolRuRHM9eNcyCRNqeEkI0uMvoKgV70zwTeq+5jnbNWlon6tdWks70tnQ17uyb59+Hi7HW6WnqyKojUdRB0WTsQ="
jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email: false
